### ISSUE TITLE
Troubles with Vault

### ISSUE THREAD

**Issue by LeMusul** [MilkBowl/VaultAPI#144]
[12:11:18 ERROR]: Error executing task on Server
me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.
LuckPerms cannot respond to the request because to do so:
- it needs to lookup user data for 'fa1a399d-c64e-3e36-93ee-9ad7fb487aee' (an offline player) from the database
Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:156) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userHasPermission(LuckPermsVaultPermission.java:175) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerHas(AbstractVaultPermission.java:151) ~[?:?]
        at com.sk89q.wepif.VaultResolver.hasPermission(VaultResolver.java:100) ~[worldedit-bukkit-7.2.10.jar:?]
        at com.sk89q.wepif.PermissionsResolverManager.hasPermission(PermissionsResolverManager.java:170) ~[worldedit-bukkit-7.2.10.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:174) ~[worldedit-bukkit-7.2.10.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at com.sk89q.worldedit.command.util.PermissionCondition.lambda$satisfied$0(PermissionCondition.java:47) ~[worldedit-bukkit-7.2.10.jar:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at com.sk89q.worldedit.command.util.PermissionCondition.satisfied(PermissionCondition.java:47) ~[worldedit-bukkit-7.2.10.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitCommandInspector.testPermission(BukkitCommandInspector.java:81) ~[worldedit-bukkit-7.2.10.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.testPermissionSilent(DynamicPluginCommand.java:100) ~[worldedit-bukkit-7.2.10.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:48) ~[purpur-1.19.jar:git-Purpur-1732]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:20) ~[purpur-1.19.jar:git-Purpur-1732]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[purpur-1.19.jar:git-Purpur-1732]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:599) ~[purpur-1.19.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:581) ~[purpur-1.19.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:908) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:994) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:820) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:891) ~[purpur-1.19.jar:git-Purpur-1732]
        at org.spigotmc.WatchdogThread.run(WatchdogThread.java:233) ~[purpur-1.19.jar:git-Purpur-1732]
        
        
        
        
        Im having this trouble and i don't know if this is crashing my server.

**Comment by cerealcable** [comment]
The error message provided by LuckyPerms is honestly really good. I'd recommend reading through the entirety of the error message and following the instructions given. This isn't a fault of Vault but how one or multiple plugins have implemented the API which isn't something Vault has control over.
